### ISSUE TITLE
How to see/extract plots, which I created  on certain day and time?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#28] opened 2016-03-29 17:37 UTC
I did 10 different runs yesterday and forgot all corresponding tags, but remember the time. I would like to see graphics from yesterday, which I created at 3 pm (or the latest).

**Comment by haji-ali** [comment] 2016-03-30 10:09
Duplicate of #22

**Closed** 2016-03-30 11:28 UTC
Labels: duplicate
