### ISSUE TITLE
My code is uspiciosly slow compare to previous

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#64] opened 2016-10-10 09:00 UTC
Can you please check it gain? (After 25000 sec. it computed only for TOL=0.5)

#!/usr/bin/python
import numpy as np
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(add_help=True)
    parser.register('type', 'bool',
                    lambda v: v.lower() in ("yes", "true", "t", "1"))
    parser.add_argument("-tries", type=int, action="store",
                        default=0, help="Number of realizations")
    parser.add_argument("-mimc_min_dim", type=int, action="store",
                        default=1, help="MIMC dim")

    args, unknowns = parser.parse_known_args()

    dim = args.mimc_min_dim
    base = "run.py -mimc_TOL {TOL} -mimc_max_TOL 3  -mimc_min_dim 1 -qoi_seed {seed} \
    -mimc_theta 0.5 -mimc_M0 5 -mimc_h0inv 3 \
    -mimc_w 2 -mimc_s 4 -mimc_gamma 1.3 -mimc_beta 2 \
    -mimc_bayes_fit_lvls 3 -mimc_moments 4 \
    -mimc_bayesian {bayesian} ".format(bayesian="{bayesian}", TOL="{TOL}", seed="{seed}")
    base += " ".join(unknowns)

    if args.tries == 0:
        cmd_single = "python " + base + " -mimc_verbose 10 -db False "
        print(cmd_single.format(seed=0, bayesian=False, TOL=0.001))
    else:
        cmd_multi = "python " + base + " -mimc_verbose 0 -db True -db_tag {tag} "
        TOL = 0.5
        for i in range(0, args.tries):
                print cmd_multi.format(bayesian=False,
                                   tag="CEM{}".format(dim), TOL=TOL,
                                   seed=np.random.randint(2**32-1))

**Comment by haji-ali** [comment] 2016-10-10 10:06
You are running TOL=0.5, so no smaller tolerances would be computed.

**Comment by haji-ali** [comment] 2016-10-12 10:10
Duplicate of #66

**Closed by haji-ali** 2016-10-12 10:10 UTC
