### ISSUE TITLE
How to run partallel version?

### ISSUE THREAD

**Issue by litvinen** [StochasticNumerics/mimclib#27] opened 2016-03-29 09:07 UTC
Only the  black-box solver is MPI parallel. It is very primitive parallelisation: first 100 columns to proc 1, columns 101-200 to proc 2 etc.

In previous C++  version
I simply added
    MPI_Init (&argc, &argv);	/* starts MPI */
    MPI_Comm_rank (MPI_COMM_WORLD, &myid);	/* get current process id */
    MPI_Comm_size (MPI_COMM_WORLD, &numprocs);	/* get number of processes */
To the main file it was Ok.

How should I proceed in the current python version?

**Comment by haji-ali** [comment] 2016-03-29 14:39
Use mpi4py to initialize MPI and be sure to run with mpirun.

**Comment by litvinen** [comment] 2016-03-29 17:15
Should I run these 3 lines
MPI_Init (&argc, &argv); /* starts MPI /
MPI_Comm_rank (MPI_COMM_WORLD, &myid); / get current process id /
MPI_Comm_size (MPI_COMM_WORLD, &numprocs); / get number of processes */
 into /CEM/echo_ file ?
What is exact syntax?

**Comment by Virtakuono** [comment] 2016-10-23 09:17
Likely duplicate of https://github.com/StochasticNumerics/mimclib/issues/82

**Closed by Virtakuono** 2016-10-23 09:17 UTC
Labels: duplicate, question
